import { useEffect } from 'react'
import Head from 'next/head'
import { loadAccount, loadWeb3 } from '../utils/interaction';
import FarmingComponent from '../components/FrmingComponent';

export default function Home() {

  useEffect(() => {
    (async()=>{
      const web3 = await loadWeb3();
      const wallet = await loadAccount(web3);
      console.log(web3);
      console.log(wallet);
    })()
  }, [])
  

  return (
    <div className='flex justify-center h-screen'>
      <Head>
        <title>Yield farming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FarmingComponent/>
    </div>
  )
}
