import { useState,useEffect } from 'react'
import Head from 'next/head'
import { loadAccount, loadBrownieTokenContract, loadTetherTokenContract, loadWeb3, loadYieldFarmingContract } from '../utils/interaction';
import FarmingComponent from '../components/FarmingComponent';

export default function Home() {

  const [web3Connection, setWeb3Connection] = useState(null);
  const [walletAddress, setWalletAddress] = useState(null);
  const [ownerAddress, setOwnerAddress] = useState(null);
  const [brownieContract, setBrownieContract] = useState(null);
  const [tetherContract, setTetherContract] = useState(null);
  const [yieldFarmingContract, setYieldFarmingContract] = useState(null);

  useEffect(() => {
    (async()=>{
      const web3 = await loadWeb3();
      const wallet = await loadAccount(web3);
      const brownieToken = await loadBrownieTokenContract(web3)
      const tetherToken = await loadTetherTokenContract(web3)
      const yieldFarming = await loadYieldFarmingContract(web3)
      
      if(yieldFarming){
        const owner = await yieldFarming.methods.owner().call();
        setOwnerAddress(owner)
      }

      setWeb3Connection(web3);
      setWalletAddress(wallet[0]);
      setBrownieContract(brownieToken);
      setTetherContract(tetherToken);
      setYieldFarmingContract(yieldFarming);
      
    })()
  }, [])

  
  return (
    <div className='flex justify-center h-screen'>
      <Head>
        <title>Yield farming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FarmingComponent
        walletAddress={walletAddress}
        web3={web3Connection}
        farmingContract={yieldFarmingContract}
        brownieContract={brownieContract}
        tetherContract={tetherContract}
        ownerAddress={ownerAddress}
      />

    </div>
  )
}
