import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='flex justify-center h-screen'>
      <Head>
        <title>Yield farming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='farming-container self-center m-2 lg:m-0'>
        <h1 className='text-xl text-white font-bold'>Brownie Yield farm</h1>
        <div className='flex justify-between pt-1'>
          <p className='text-sm text-white'><strong className='font-bold'>Wallet balance :</strong> 100 ETH</p>
          <p className='text-sm text-white font-bold w-20 lg:w-40 truncate'>0x495f264d1c096D55ef3f2.....</p>
        </div>

        <div className='flex justify-between pt-6 lg:pt-12'>
          <div className='p-3 bg-[#72737D] w-2/5 rounded-md'>
            <p className='text-white'><strong className='font-bold'>Staking balance</strong> 100</p>
          </div>
          <div className='p-3 bg-[#72737D] w-2/5 rounded-md'>
            <p className='text-white'><strong className='font-bold'>Staking balance</strong> 100</p>
          </div>
        </div>

        <div className="flex flex-row pt-6">
            <input type="number" placeholder="Type here" className="input rounded-l-md" />
            <span className="input-btn-label" >
               Tether
            </span>
        </div>

      </div>

    </div>
  )
}
